---
# tasks file for NGINX

- name: Update and upgrade apt packages
  ansible.builtin.apt:
  #  upgrade: "yes"
    update_cache: true

- name: Allow TCP ports
  ansible.builtin.iptables:
    chain: INPUT
    rule_num: '1'
    action: insert
    protocol: TCP
    jump: ACCEPT
    destination_port: "80"   

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: "yes"
  
- name: Create file nginx.conf
  ansible.builtin.template:
    src: "templates/templates_nginx_conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify: Enabled Nginx

